name: PR Preview Deployment

on:
  pull_request:
    branches:
      - main  # Change as needed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies & Build
        run: |
          npm install --force
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy PR Build to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }}/previews/pr-${{ github.event.pull_request.number }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/previews/pr-${{ github.event.pull_request.number }}/*"

      - name: Comment Preview URL on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://${{ secrets.CLOUDFRONT_DOMAIN }}/previews/pr-${prNumber}/index.html`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview URL: [Click Here](${previewUrl})`
            });

  cleanup-on-close:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Remove PR Preview from S3
        run: aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }}/previews/pr-${{ github.event.pull_request.number }} --recursive
